### ISSUE TITLE
README update: ArchLinux AUR package

### ISSUE THREAD

**Issue by JSkier21** [StamusNetworks/gophercap#1]
I have created an AUR package for ArchLinux here:
https://aur.archlinux.org/packages/gophercap/

Feel free to update the README file to include installation via user build with makepkg or using yay:
`yay- S gophercap`

**Comment by markuskont** [comment]
This is really cool. I will add it to README soon.  Just a few minor notes.

We just embedded a version number with binary for our own deployments. Consider using this in PKGBUILD 
```
go build -ldflags="-X 'gopherCap/cmd.Version=$pkgver'" -o ./$pkgname ./
```

That way, `gophercap version` outputs correct build tag.

I also suggest adding libpcap as dependency. The writer currently needs it. If missing, then `makepkg` would fail I guess.

**Comment by JSkier21** [comment]
Not a problem, I added the additional build details, works great, thank you.

**Comment by markuskont** [comment]
Reference has been added to the contributed AUR package. Thanks a lot!

https://github.com/StamusNetworks/gophercap#arch-linux

Happy to close the issue.
