### ISSUE TITLE
Feature Request - Filtering - ASN based filtering

### ISSUE THREAD

**Issue by zoomequipd** [StamusNetworks/gophercap#3]
Often time when filtering large pcaps gathered from Windows networks, I find myself spending a lot of time filtering out traffic between the monitored network and Microsoft, largely sourced from update checks and telemetry data. 

The ability to filter based on ASN would make quick work of removing this traffic. 

However, because Microsoft also has ASN for public hosting (Azure) I often have to explicitly include the traffic from [Microsoft's Public Cloud IP list](https://www.microsoft.com/en-us/download/details.aspx?id=56519).  I'll create another feature request for "Negation Support" that when combined with ASN filtering would make very quick work of this typical "pre-filtering" effort.

**Comment by markuskont** [comment]
This has been implemented in latest master.
