### ISSUE TITLE
Feature Request - Filtering - Negation Support

### ISSUE THREAD

**Issue by zoomequipd** [StamusNetworks/gophercap#4]
When filtering large pcaps collected from Windows based networks, I often find myself removing traffic to/from Microsoft owned networks in effort to remove telemetry "noise" from the pcap.  However, because Microsoft also host public cloud infrastructure, I am required to "Negate" traffic that is to/from the public cloud ranges.  

It would be nice to allow filter "negations" which would explicitly NOT filter the traffic out. For instance, if I want to filter out all traffic involving "13.64.0.0/11" but keep "13.70.0.0/18"

In this case, I use IPs, but it would be nice to combine the filter and negation support between types of filtering.  Filter on subnets and allow for negation on ports, etc.

**Comment by markuskont** [comment]
Yes, I like this idea. I'm thinking we should ditch the `--filter-mode` flag and enhance the filter YAML to support any number of filters. Filter kind and modifiers such as negation could be specified per filter.

**Comment by markuskont** [comment]
This has been implemented in latest master.
